# Generated by Django 3.1 on 2020-09-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, help_text='Optional (e.g.Fashion, Toys, Electronics, Home, etc.)', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(help_text='Tell users more about your product! (Hint, make it interesting) ', max_length=2048),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, help_text='Optional, but if you want to include an image for your product, please include an online url for it here!', max_length=2048),
        ),
    ]
